/*

The sequence of triangle numbers is generated by adding the natural numbers.
So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

 1: 1
 3: 1,3
 6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28
We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?

*/
export function divisores(number:number):number {
  let div = 0;
  for (let i = 1; i * i <= number; i += 2) {
    if (number % i === 0) div += 1;
  }
  return div;
}

let i = 0;
let s = 0;
while (true) {
  i += 1;
  s = (i * (i + 1)) / 2;

  if (divisores(s) === 500) {
    break;
  }
}
console.log(s);
